#========== civcraft.net Server Listing Service (SLS) ==========#
use_server_listing_service: 'false'
#
server_address: "LocalHost"
server_address_url: 'https://www.youtube.com/user/cpcole556'
server_address_url_description: 'YourCoal''s YouTube'
#
server_name: 'CivCraft'
server_name_url: 'https://www.youtube.com/user/cpcole556'
server_name_url_description: 'YourCoal''s YouTube'
#
server_timezone: 'CST'
#
server_description: 'Dev. Build 1.0.4 of YourCoal''s CivCraft Project.'
#
debug_heartbeat: 'false'
#=============== Database Configuration ===============#
mysql:
   hostname: localhost
   port: '3306'
   database: 'game'
   username: root
   password: 1234
   table_prefix: ''
   min_conns: '5'
   max_conns: '10'
   parts: '3'
#
global_database:
    database: 'global'
    hostname: localhost
    port: '3306'
    username: 'root'
    password: 1234
    min_conns: '5'
    max_conns: '10'
    parts: '3'
#
server_phase: 'TestServer'